In try
Caught: Error!
Finally executes